// Shift Actions
export const CREATE_SHIFT_REQUEST = "CREATE_SHIFT_REQUEST";
export const CREATE_SHIFT_SUCCESS = "CREATE_SHIFT_SUCCESS";
export const CREATE_SHIFT_FAILURE = "CREATE_SHIFT_FAILURE";

export const UPDATE_SHIFT_REQUEST = "UPDATE_SHIFT_REQUEST";
export const UPDATE_SHIFT_SUCCESS = "UPDATE_SHIFT_SUCCESS";
export const UPDATE_SHIFT_FAILURE = "UPDATE_SHIFT_FAILURE";

export const DELETE_SHIFT_REQUEST = "DELETE_SHIFT_REQUEST";
export const DELETE_SHIFT_SUCCESS = "DELETE_SHIFT_SUCCESS";
export const DELETE_SHIFT_FAILURE = "DELETE_SHIFT_FAILURE";

export const GET_SHIFT_REQUEST = "GET_SHIFT_REQUEST";
export const GET_SHIFT_SUCCESS = "GET_SHIFT_SUCCESS";
export const GET_SHIFT_FAILURE = "GET_SHIFT_FAILURE";

export const GET_ALL_SHIFTS_REQUEST = "GET_ALL_SHIFTS_REQUEST";
export const GET_ALL_SHIFTS_SUCCESS = "GET_ALL_SHIFTS_SUCCESS";
export const GET_ALL_SHIFTS_FAILURE = "GET_ALL_SHIFTS_FAILURE";

export const GET_WORKER_SHIFTS_REQUEST = "GET_WORKER_SHIFTS_REQUEST";
export const GET_WORKER_SHIFTS_SUCCESS = "GET_WORKER_SHIFTS_SUCCESS";
export const GET_WORKER_SHIFTS_FAILURE = "GET_WORKER_SHIFTS_FAILURE";

export const GET_RESTAURANT_SHIFTS_REQUEST = "GET_RESTAURANT_SHIFTS_REQUEST";
export const GET_RESTAURANT_SHIFTS_SUCCESS = "GET_RESTAURANT_SHIFTS_SUCCESS";
export const GET_RESTAURANT_SHIFTS_FAILURE = "GET_RESTAURANT_SHIFTS_FAILURE";

// Shift Status Actions
export const CHECK_IN_SHIFT_REQUEST = "CHECK_IN_SHIFT_REQUEST";
export const CHECK_IN_SHIFT_SUCCESS = "CHECK_IN_SHIFT_SUCCESS";
export const CHECK_IN_SHIFT_FAILURE = "CHECK_IN_SHIFT_FAILURE";

export const CHECK_OUT_SHIFT_REQUEST = "CHECK_OUT_SHIFT_REQUEST";
export const CHECK_OUT_SHIFT_SUCCESS = "CHECK_OUT_SHIFT_SUCCESS";
export const CHECK_OUT_SHIFT_FAILURE = "CHECK_OUT_SHIFT_FAILURE";

export const CANCEL_SHIFT_REQUEST = "CANCEL_SHIFT_REQUEST";
export const CANCEL_SHIFT_SUCCESS = "CANCEL_SHIFT_SUCCESS";
export const CANCEL_SHIFT_FAILURE = "CANCEL_SHIFT_FAILURE";

export const UPDATE_SHIFT_STATUS_REQUEST = "UPDATE_SHIFT_STATUS_REQUEST";
export const UPDATE_SHIFT_STATUS_SUCCESS = "UPDATE_SHIFT_STATUS_SUCCESS";
export const UPDATE_SHIFT_STATUS_FAILURE = "UPDATE_SHIFT_STATUS_FAILURE";
