// Worker Actions
export const CREATE_WORKER_REQUEST = "CREATE_WORKER_REQUEST";
export const CREATE_WORKER_SUCCESS = "CREATE_WORKER_SUCCESS";
export const CREATE_WORKER_FAILURE = "CREATE_WORKER_FAILURE";

export const UPDATE_WORKER_REQUEST = "UPDATE_WORKER_REQUEST";
export const UPDATE_WORKER_SUCCESS = "UPDATE_WORKER_SUCCESS";
export const UPDATE_WORKER_FAILURE = "UPDATE_WORKER_FAILURE";

export const DELETE_WORKER_REQUEST = "DELETE_WORKER_REQUEST";
export const DELETE_WORKER_SUCCESS = "DELETE_WORKER_SUCCESS";
export const DELETE_WORKER_FAILURE = "DELETE_WORKER_FAILURE";

export const GET_WORKER_REQUEST = "GET_WORKER_REQUEST";
export const GET_WORKER_SUCCESS = "GET_WORKER_SUCCESS";
export const GET_WORKER_FAILURE = "GET_WORKER_FAILURE";

export const GET_ALL_WORKERS_REQUEST = "GET_ALL_WORKERS_REQUEST";
export const GET_ALL_WORKERS_SUCCESS = "GET_ALL_WORKERS_SUCCESS";
export const GET_ALL_WORKERS_FAILURE = "GET_ALL_WORKERS_FAILURE";

export const TOGGLE_WORKER_STATUS_REQUEST = "TOGGLE_WORKER_STATUS_REQUEST";
export const TOGGLE_WORKER_STATUS_SUCCESS = "TOGGLE_WORKER_STATUS_SUCCESS";
export const TOGGLE_WORKER_STATUS_FAILURE = "TOGGLE_WORKER_STATUS_FAILURE";

// Worker Login
export const WORKER_LOGIN_REQUEST = "WORKER_LOGIN_REQUEST";
export const WORKER_LOGIN_SUCCESS = "WORKER_LOGIN_SUCCESS";
export const WORKER_LOGIN_FAILURE = "WORKER_LOGIN_FAILURE";
export const WORKER_LOGOUT = "WORKER_LOGOUT";
